version: 2
jobs:
   build:
     docker:
       - image: danteev/texlive
     steps:
       - checkout
       - run: ./download-llncs-files-from-springer.sh
       # create paper-*-lmodern.pdf
       - run: latexmk paper.tex && mv paper.pdf paper-lmodern.pdf
       - run: latexmk paper-minted.tex && mv paper-minted.pdf paper-minted-lmodern.pdf
       # activate usage of newtxmath and create paper-*-newtx.pdf
       - run: sed -i "s/iftrue % use default-font/iffalse/" paper.tex
       - run: latexmk paper.tex && mv paper.pdf paper-newtx.pdf
       - run: sed -i "s/iftrue % use default-font/iffalse/" paper-minted.tex
       - run: latexmk paper-minted.tex && mv paper-minted.pdf paper-minted-newtx.pdf
       # collect results in build/ folder
       - run: mv paper-lmodern.pdf paper.pdf && mv paper-minted-lmodern.pdf paper-minted.pdf && mkdir build && cp -r README.md paper*.pdf .github/_config.yml build/
       # store and publish build results
       - store_artifacts:
           path: build/
       - store_artifacts:
           path: llncs.cls
       - store_artifacts:
           path: splncs03.bst
       - run: if [ "$CIRCLE_BRANCH" == "master" ]; then .circleci/deploy-ghpages.sh build/; fi
       # remove generated files
       - run: latexmk -c paper
       - run: latexmk -c paper-minted
       # try compilation with lualatex
       # ensure that --shell-escape is only needed at paper-minted.tex
       - run: lualatex paper.tex
       - run: lualatex --shell-escape paper-minted.tex
       # full compilation with latexmk
       - run: sed -i "s|$pdflatex = 'pdflatex|$pdflatex = 'lualatex|" .latexmkrc
       - run: latexmk paper
       - run: latexmk paper-minted
